### PR TITLE
Support HTTP/2 protocol.

### LINKED ISSUE #25: Support HTTP/2.
Base on https://github.com/netty/netty/tree/4.1/codec-http2.

### PR DESCRIPTION
**Pull request by ujjboy**
### Motivation:

Support HTTP/1.1 & HTTP/2 protocol.

### Modification:
- Add HTTP/1.1 server & HTTP/2 Clear text server
- Add HTTP/2 client transport.
 
### Result:
Fix #25

### CODE REVIEW

**Comment by leizhiyuan** [comment]
It seems tracer is ok 
client
```
{"timestamp":"2018-05-27 18:43:48.681","tracerId":"0a4187b11527417826069100199533","spanId":"0","span.kind":"client","local.app":"test-client","protocol":"h2c","service":"com.alipay.sofa.rpc.protobuf.ProtoService","method":"echoObj","current.thread.name":"main","invoke.type":"sync","router.record":"DIRECT","remote.ip":"127.0.0.1:12300","local.client.ip":"127.0.0.1","result.code":"00","req.serialize.time":"1206","req.size":"5","client.elapse.time":"1844","local.client.port":"54560","baggage":""}

```

server
```
{"timestamp":"2018-05-27 18:43:47.253","tracerId":"","spanId":"","span.kind":"server","service":"com.alipay.sofa.rpc.protobuf.ProtoService","method":"echoObj","remote.ip":"127.0.0.1","remote.app":"test-client","protocol":"h2c","local.app":"test-server","current.thread.name":"SOFA-SEV-H2C-BIZ-12300-3-T1","result.code":"00","biz.impl.time":"3","baggage":""}

```

**Comment by leizhiyuan** [comment]
image

netty convert header to lowercase. when we receive in server.

rpc_trace_context.sofaRpcId will become rpc_trace_context.sofarpcid

**Comment by ujjboy** [comment]
@leizhiyuan I have fixed it. See `com.alipay.sofa.rpc.transport.http.HttpTracerUtils`.

**Comment by leizhiyuan** [comment]
@ujjboy 
```
{"timestamp":"2018-05-28 06:34:01.173","tracerId":"c0a8016c152746044116910138939","spanId":"0","span.kind":"server","service":"com.alipay.sofa.rpc.protobuf.ProtoService","method":"echoObj","remote.ip":"127.0.0.1","remote.app":"test-client","protocol":"h2c","local.app":"test-server","current.thread.name":"SOFA-SEV-H2C-BIZ-12300-3-T2","result.code":"00","biz.impl.time":"0","baggage":""}
```
now, tracer is ok

**Pull request merged**
